### PR TITLE
Also parse YAML as mapping file

### PR DESCRIPTION
**Pull request by yohanboniface**
Ref #55

This is a quite naive approach, given that I've never written a single go line in the past ;)

It uses https://github.com/ghodss/yaml, which maps with internal go json parser.

I've chosen to test against yml (so loading `test_mapping.yml`) instead of json, given that json is valid yaml. Note that when keeping the json file, tests pass also. Maybe we want to run the tests against both yaml and json, but that seems overkill to me, for the same reason that json is valid yaml.

Thanks for your review and feedback :)

### CODE REVIEW

**Comment by olt** [comment]
Thanks. 
But I'd rather change the `json` tags to `yaml` then to maintain an additional dependency, since ghodss/yaml is just a wrapper for go-yaml/yaml.
Could you also update the examples with the new enumerate type and remove all lines with ``null`` values?

**Comment by yohanboniface** [comment]
> But I'd rather change the json tags to yaml then to maintain an additional dependency, since 
> ghodss/yaml is just a wrapper for go-yaml/yaml.

Humm, this will means switching all the marshall/unmarshall methods too, right? I wonder if this will not ends with a code less DRY, what do you think?

Again, my go is zero, I'm relying on those explanations http://ghodss.com/2014/the-right-way-to-handle-yaml-in-golang/ so I may be totally missing the point ;)

> Could you also update the examples with the new enumerate type and remove all lines with null 
> values?

Sure :) I wanted to wait until the code will be ok before spending time on changing the doc, but I will for sure!

**Comment by olt** [comment]
> Humm, this will means switching all the marshall/unmarshall methods too, right? I wonder if this will not ends with a code less DRY, what do you think?

Not sure what you mean with that. You need to change the single Unmarshal call to use the gopkg.in/yaml.v2 package. And you also need to change `` `json:"name"` `` to `` `yaml:"name"` ``, etc.

**Comment by yohanboniface** [comment]
> Not sure what you mean with that. 

I was referring to the `UnmarshalJSON` func, but let's go ahead and see what I'll hit ;)

**Comment by yohanboniface** [comment]
Humm, strangely, it fails loading this yaml piece when using a yaml tag (```ExcludeTags *[][2]string `yaml:"exclude_tags"```):

```
    filters:
      exclude_tags:
      - ["area", "yes"]
```

While it loads when keeping the original version ```ExcludeTags *[][2]string `json:"exclude_tags"````

Message is not that helpful: `line 481: cannot unmarshal !!seq into [2]string`

Investigating.

**Comment by yohanboniface** [comment]
@olt updated the PR.

Some remarks:

- Needed to change this line:

    ```ExcludeTags *[][2]string `yaml:"exclude_tags"````

  to:

     ```ExcludeTags *[][]string `yaml:"exclude_tags"````

  Dunno why. Tests pass.

- I've updated the doc, and chosen to keep in flow styles the small mappings and sequences, as this seems to me the more readable and maintenable version; if you prefer a strict yaml structure, I can make the change

- we may also use yaml for the config file?

**Comment by olt** [comment]
Thanks a lot for your contribution!
I've rebased your commits, added the yaml package to godeps and updated the example a bit.
Go a head if you want to update the config loader as well. Just make sure you create a new branch from the updated master branch!

**Comment by yohanboniface** [comment]
Excellent, thanks! :)

**Pull request closed without merging**
